
import { motion, AnimatePresence } from 'framer-motion';
import { X, BookOpen, Loader } from 'lucide-react';

interface DeepDiveModalProps {
    isOpen: boolean;
    onClose: () => void;
    content: string | null;
    isLoading: boolean;
    symbol: string;
}

export default function DeepDiveModal({ isOpen, onClose, content, isLoading, symbol }: DeepDiveModalProps) {
    if (!isOpen) return null;

    return (
        <AnimatePresence>
            <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
                <motion.div
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.95 }}
                    className="w-full max-w-2xl bg-[#0a0a0f] border border-white/10 rounded-2xl shadow-2xl max-h-[85vh] overflow-hidden flex flex-col"
                >
                    {/* Header */}
                    <div className="p-6 border-b border-white/10 flex items-center justify-between bg-white/[0.02]">
                        <div className="flex items-center gap-3">
                            <div className="p-2 bg-purple-500/20 rounded-lg">
                                <BookOpen size={20} className="text-purple-400" />
                            </div>
                            <div>
                                <h2 className="text-xl font-bold text-white">Deep Dive Analysis</h2>
                                <p className="text-xs text-gray-400">Institutional Structural Report • {symbol}</p>
                            </div>
                        </div>
                        <button
                            onClick={onClose}
                            className="p-2 hover:bg-white/10 rounded-lg transition-colors text-gray-400 hover:text-white"
                        >
                            <X size={20} />
                        </button>
                    </div>

                    {/* Content */}
                    <div className="p-6 overflow-y-auto custom-scrollbar flex-1">
                        {isLoading ? (
                            <div className="flex flex-col items-center justify-center py-20 space-y-4">
                                <Loader size={32} className="text-purple-400 animate-spin" />
                                <p className="text-gray-400 text-sm animate-pulse">Generating Professor's Report...</p>
                            </div>
                        ) : content ? (
                            <div className="prose prose-invert prose-sm max-w-none">
                                {content.split('# ').map((section, i) => {
                                    if (!section.trim()) return null;
                                    const lines = section.trim().split('\n');
                                    const title = lines[0];
                                    const body = lines.slice(1).join('\n');
                                    return (
                                        <div key={i} className="mb-8 last:mb-0">
                                            <h3 className="text-lg font-bold text-purple-200 mb-3 border-l-2 border-purple-500 pl-3">
                                                {title}
                                            </h3>
                                            <div className="text-gray-300 leading-relaxed whitespace-pre-wrap">
                                                {body}
                                            </div>
                                        </div>
                                    );
                                })}
                                {!content.includes('# ') && <p className="whitespace-pre-wrap text-gray-300">{content}</p>}
                            </div>
                        ) : (
                            <div className="text-center text-gray-500 py-10">
                                Unable to load analysis.
                            </div>
                        )}
                    </div>

                    {/* Footer */}
                    <div className="p-4 border-t border-white/10 bg-white/[0.02] text-center">
                        <p className="text-[10px] text-gray-500">
                            Generated by Zenith AI (Professor Model). Not financial advice.
                        </p>
                    </div>
                </motion.div>
            </div>
        </AnimatePresence>
    );
}
